Add Functionality
Snayak7643/Tours pull request #1
Opened 2023-01-06 12:08 UTC by Snayak7643

2023-01-06 12:26 UTC, Ishaan-flyfin requested changes
nice progress!
added some minor comments

2023-01-06 12:26 UTC, Ishaan-flyfin commented on src/App.tsx
> +type Tour = {
nice!

2023-01-06 12:26 UTC, Ishaan-flyfin commented on src/App.tsx
> +  const fetching = async () => {
we can give a better name
something which tells what we are fetching here

2023-01-06 12:26 UTC, Ishaan-flyfin commented on src/App.tsx
> +  };
nice

2023-01-06 12:26 UTC, Ishaan-flyfin commented on src/App.tsx
> +  }, []);
here we can think of usecallback usage
lets discuss this in call

2023-01-06 12:26 UTC, Ishaan-flyfin commented on src/App.tsx
> +    const response = await fetch(url);
we can add api error handling also

2023-01-06 12:26 UTC, Ishaan-flyfin commented on src/Components/Card.tsx
> +  };
we can create a file `types.ts`
in which we can export reusable types like tour which is being used in app.tsx and card.tsx

2023-01-06 12:26 UTC, Ishaan-flyfin commented on src/Components/Card.tsx
> +const Card: React.FunctionComponent<PropType> = ({ tour, deleteTour }) => {
instead  of tour, we can pass specific props which makes this component more reusable

2023-01-06 13:45 UTC, Snayak7643 commented on src/Components/Card.tsx
> +  };
Done

2023-01-06 13:46 UTC, Snayak7643 commented on src/App.tsx
> +    const response = await fetch(url);
Done

2023-01-06 13:46 UTC, Snayak7643 commented on src/App.tsx
> +  const fetching = async () => {
Renamed to fetchingTours

2023-01-07 05:23 UTC, Ishaan-flyfin approved these changes

2023-01-09 08:27 UTC, merged